name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        flutter config --enable-web
        flutter pub get
        
    - name: Build web app
      run: flutter build web --release --web-renderer canvaskit --base-href="/school_managment_flutter/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        publish_branch: gh-pages
        force_orphan: true