name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Get dependencies
      run: |
        flutter config --enable-web
        flutter pub get

    - name: Build web app
      run: flutter build web --release --dart-define=FLUTTER_WEB_RENDERER=canvaskit --base-href="/school_managment_flutter/"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/web'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4